### PR TITLE
Team page added

### PR DESCRIPTION
**Pull request by NoOne-Cares**
Team page completed

### CODE REVIEW

**Review by JOSU9435 — CHANGES_REQUESTED** [review]
image

- center the image and text properly
- make the transition a bit smoother 
- in phone view remove focus and leave it as hover

**Review by JOSU9435 — CHANGES_REQUESTED** [review]
- center the **text** also on hover
image

- socials are not properly visible on some phones try giving the 3rd line less font size

**Comment by NoOne-Cares** [comment]
- [x] fixed socials visibility
- [x] fixed text alignments of text.

**Comment by JOSU9435** [comment]
image

socials are still not visible in this phone

**Comment by JOSU9435** [comment]
image

- Remove this * {} selector and fix everything again. Due to this selector all the styles of the website are messed up

**Review by JOSU9435 — APPROVED** [review]

**Pull request merged**
